### ISSUE TITLE
Work/Day views not working

### ISSUE THREAD

**Issue by IuliaDam** [maqsoftware/CalendarVisual#6]
Hi,

I've been trying to use the Calendar Visual by MAQ Software and I keep encountering the following issue:

While Month and List views work perfectly
![image](https://user-images.githubusercontent.com/69978842/90793318-441fb080-e314-11ea-8f14-5f0d4202008d.png)
![image](https://user-images.githubusercontent.com/69978842/90793356-4eda4580-e314-11ea-9fb4-50a37ce8249f.png)

Week and Day views won't work no matter what I do
![image](https://user-images.githubusercontent.com/69978842/90793463-6f0a0480-e314-11ea-9c9a-58cd66f46630.png)
![image](https://user-images.githubusercontent.com/69978842/90793513-7af5c680-e314-11ea-83cf-4a7397237648.png)

Has anyone else encountered this? Any idea how to fix it?

Thanks!

**Comment by hnhn789** [comment]
Same problem here. Week and Day views had not been showing properly since last week.

**Comment by Domenyk** [comment]
I have the same issue - Using the Edge Browser and the Power BI Mobile App

**Comment by fir3nzo** [comment]
We have the same issue. Week view stacks all the events in one place while the day view is blank.

**Comment by jay-o** [comment]
having the same issue here with no successful workarounds discovered so far. any tips?

**Comment by mihailorajacic** [comment]
Having the same issue with week and day views recently. Any updates on this one?

**Comment by djbeal130** [comment]
Same issue here.

**Comment by RoSiCzech** [comment]
Same problem here.

**Comment by MeghaDesai** [comment]
Hello Everyone, we have published a fix for the same on App Source. It typically takes about 6 weeks for the published version to reflect. We have an internal build available. If you have an urgent need, please drop an email to support@maqsoftware.com and we should be able to provide that to you.

**Comment by csteelatgburg** [comment]
Can you provide some transparency on version numbers? The latest update on the repo was nine months ago, which doesn't match your comment from August 30th, unless you aren't updating the repo when you update the code with App Source. My visual shows it is using version 3.1.0.1 and I am still experiencing the issue of events not showing on the week view, although some of them are now showing on the day view. Should that version have the fix for this issue?

**Comment by IuliaDam** [comment]
> Can you provide some transparency on version numbers? The latest update on the repo was nine months ago, which doesn't match your comment from August 30th, unless you aren't updating the repo when you update the code with App Source. My visual shows it is using version 3.1.0.1 and I am still experiencing the issue of events not showing on the week view, although some of them are now showing on the day view. Should that version have the fix for this issue?

I am encountering the same situation. The app still isn't working for days and weeks view.
